import {
  AlbumItem,
  ArtistAlbumItem,
  ArtistItem,
  ArtistTrackItem,
  PlaylistItem,
  TrackItem,
} from "./types/component";

const mockPlaylists: PlaylistItem[] = [
  {
    id: "pl1",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    name: "Chill Hits",
    tracks: { href: "https://api.example.com/playlists/pl1/tracks", total: 0 },
    type: "playlist",
    href: "https://api.example.com/playlists/pl1",
  },
  {
    id: "pl2",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    name: "Rock Classics",
    tracks: { href: "https://api.example.com/playlists/pl2/tracks", total: 30 },
    type: "playlist",
    href: "https://api.example.com/playlists/pl2",
  },
  {
    id: "pl3",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    name: "Pop Party",
    tracks: { href: "https://api.example.com/playlists/pl3/tracks", total: 40 },
    type: "playlist",
    href: "https://api.example.com/playlists/pl3",
  },
  {
    id: "pl4",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    name: "Jazz Vibes",
    tracks: { href: "https://api.example.com/playlists/pl4/tracks", total: 25 },
    type: "playlist",
    href: "https://api.example.com/playlists/pl4",
  },
  {
    id: "pl5",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    name: "Indie Mix",
    tracks: { href: "https://api.example.com/playlists/pl5/tracks", total: 35 },
    type: "playlist",
    href: "https://api.example.com/playlists/pl5",
  },
  {
    id: "pl6",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    name: "Indie Mix",
    tracks: { href: "https://api.example.com/playlists/pl5/tracks", total: 35 },
    type: "playlist",
    href: "https://api.example.com/playlists/pl5",
  },
  {
    id: "pl7",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    name: "Indie Mix",
    tracks: { href: "https://api.example.com/playlists/pl5/tracks", total: 35 },
    type: "playlist",
    href: "https://api.example.com/playlists/pl5",
  },
];

const mockAlbums: AlbumItem[] = [
  {
    id: "al1",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    name: "Summer Tunes",
    total_tracks: 12,
    type: "album",
    href: "https://api.example.com/albums/al1",
  },
  {
    id: "al2",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    name: "Winter Ballads",
    total_tracks: 10,
    type: "album",
    href: "https://api.example.com/albums/al2",
  },
  {
    id: "al3",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    name: "City Lights",
    total_tracks: 15,
    type: "album",
    href: "https://api.example.com/albums/al3",
  },
  {
    id: "al4",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    name: "Road Trip",
    total_tracks: 8,
    type: "album",
    href: "https://api.example.com/albums/al4",
  },
  {
    id: "al5",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    name: "Night Drive",
    total_tracks: 14,
    type: "album",
    href: "https://api.example.com/albums/al5",
  },
];

const mockArtists: ArtistItem[] = [
  {
    id: "ar1",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    name: "John Doe",
    type: "artist",
    href: "https://api.example.com/artists/ar1",
  },
  {
    id: "ar2",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    name: "Jane Smith",
    type: "artist",
    href: "https://api.example.com/artists/ar2",
  },
  {
    id: "ar3",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    name: "The Band",
    type: "artist",
    href: "https://api.example.com/artists/ar3",
  },
  {
    id: "ar4",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    name: "Emma Wilson",
    type: "artist",
    href: "https://api.example.com/artists/ar4",
  },
];

const mockTracks: TrackItem[] = [
  {
    id: "track1",
    name: "Sunset Dreams",
    album: {
      id: "al1",
      images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
      name: "Summer Tunes",
      total_tracks: 12,
      type: "album",
      href: "https://api.example.com/albums/al1",
    },
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    artists: [
      {
        id: "ar1",
        images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
        name: "John Doe",
        type: "artist",
        href: "https://api.example.com/artists/ar1",
      },
    ],
    duration_ms: 180000, // 3 phút
    explicit: false,
    href: "https://api.example.com/tracks/track1",
    track_number: 1,
    type: "track",
  },
  {
    id: "track2",
    name: "Moonlight Vibes",
    album: {
      id: "al2",
      images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
      name: "Winter Ballads",
      total_tracks: 10,
      type: "album",
      href: "https://api.example.com/albums/al2",
    },
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    artists: [
      {
        id: "ar2",
        images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
        name: "Jane Smith",
        type: "artist",
        href: "https://api.example.com/artists/ar2",
      },
    ],
    duration_ms: 210000, // 3 phút 30 giây
    explicit: true,
    href: "https://api.example.com/tracks/track2",
    track_number: 2,
    type: "track",
  },
  {
    id: "track3",
    name: "City Lights",
    album: {
      id: "al3",
      images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
      name: "City Lights",
      total_tracks: 15,
      type: "album",
      href: "https://api.example.com/albums/al3",
    },
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    artists: [
      {
        id: "ar3",
        images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
        name: "The Band",
        type: "artist",
        href: "https://api.example.com/artists/ar3",
      },
    ],
    duration_ms: 165000, // 2 phút 45 giây
    explicit: false,
    href: "https://api.example.com/tracks/track3",
    track_number: 3,
    type: "track",
  },
  {
    id: "track4",
    name: "Road Trip Anthem",
    album: {
      id: "al4",
      images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
      name: "Road Trip",
      total_tracks: 8,
      type: "album",
      href: "https://api.example.com/albums/al4",
    },
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    artists: [
      {
        id: "ar4",
        images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
        name: "Emma Wilson",
        type: "artist",
        href: "https://api.example.com/artists/ar4",
      },
    ],
    duration_ms: 195000, // 3 phút 15 giây
    explicit: false,
    href: "https://api.example.com/tracks/track4",
    track_number: 1,
    type: "track",
  },
  {
    id: "track5",
    name: "Night Drive",
    album: {
      id: "al5",
      images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
      name: "Night Drive",
      total_tracks: 14,
      type: "album",
      href: "https://api.example.com/albums/al5",
    },
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    artists: [
      {
        id: "ar5",
        images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
        name: "Cool Vibes",
        type: "artist",
        href: "https://api.example.com/artists/ar5",
      },
    ],
    duration_ms: 240000, // 4 phút
    explicit: true,
    href: "https://api.example.com/tracks/track5",
    track_number: 5,
    type: "track",
  },
  {
    id: "track6",
    name: "Night Drive",
    album: {
      id: "al5",
      images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
      name: "Night Drive",
      total_tracks: 14,
      type: "album",
      href: "https://api.example.com/albums/al5",
    },
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    artists: [
      {
        id: "ar5",
        images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
        name: "Cool Vibes",
        type: "artist",
        href: "https://api.example.com/artists/ar5",
      },
    ],
    duration_ms: 240000, // 4 phút
    explicit: true,
    href: "https://api.example.com/tracks/track5",
    track_number: 5,
    type: "track",
  },
];

const mockData = [
  {
    id: 1,
    title: "Playlist made for you",
    data: mockPlaylists,
  },
  {
    id: 2,
    title: "You may have interest",
    data: mockTracks,
  },
  {
    id: 3,
    title: "Latest albums",
    data: mockAlbums,
  },
  {
    id: 4,
    title: "Popular artists",
    data: mockArtists,
  },
  {
    id: 5,
    title: "Your playlists",
    data: mockPlaylists,
  },
  {
    id: 6,
    title: "Your saved albums",
    data: mockAlbums,
  },
  {
    id: 7,
    title: "Your saved artists",
    data: mockArtists,
  },
];

const mockArtistTracks: ArtistTrackItem[] = [
  {
    id: "at_01",
    name: "Midnight Dreams",
    type: "track",
    href: "/tracks/at_01",
    duration_ms: 237000, // 3:57
    explicit: false,
    track_number: 1,
    uploadTime: "2025-05-10T14:23:45Z",
    status: "active",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    album: {
      id: "al1",
      images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
      name: "Summer Tunes",
      total_tracks: 12,
      type: "album",
      href: "https://api.example.com/albums/al1",
    },
  },
  {
    id: "at_02",
    name: "Ocean Waves",
    type: "track",
    href: "/tracks/at_02",
    duration_ms: 184000, // 3:04
    explicit: false,
    track_number: 3,
    uploadTime: "2025-06-02T09:12:30Z",
    status: "inactive",
    images: [{ url: "https://picsum.photos/200s", height: 200, width: 200 }],
    album: {
      id: "al2",
      images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
      name: "Winter Ballads",
      total_tracks: 10,
      type: "album",
      href: "https://api.example.com/albums/al2",
    },
  },
  {
    id: "at_03",
    name: "Electric Soul",
    type: "track",
    href: "/tracks/at_03",
    duration_ms: 305000, // 5:05
    explicit: true,
    track_number: 2,
    uploadTime: "2025-05-28T16:45:12Z",
    status: "active",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    album: {
      id: "al3",
      images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
      name: "City Lights",
      total_tracks: 15,
      type: "album",
      href: "https://api.example.com/albums/al3",
    },
  },
  {
    id: "at_04",
    name: "Lost Highway",
    type: "track",
    href: "/tracks/at_04",
    duration_ms: 219000, // 3:39
    explicit: false,
    track_number: 5,
    uploadTime: "2025-06-05T10:30:00Z",
    status: "active",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    album: {
      id: "al4",
      images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
      name: "Road Trip",
      total_tracks: 8,
      type: "album",
      href: "https://api.example.com/albums/al4",
    },
  },
  {
    id: "at_05",
    name: "Neon Lights",
    type: "track",
    href: "/tracks/at_05",
    duration_ms: 268000, // 4:28
    explicit: true,
    track_number: 1,
    uploadTime: "2025-06-01T20:15:45Z",
    status: "inactive",
    images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
    album: {
      id: "al4",
      images: [{ url: "https://picsum.photos/200", height: 200, width: 200 }],
      name: "Road Trip",
      total_tracks: 8,
      type: "album",
      href: "https://api.example.com/albums/al4",
    },
  },
];

const mockArtistAlbums: ArtistAlbumItem[] = [
  {
    id: "alb_001",
    name: "Midnight Memories",
    total_tracks: 3,
    href: "/album/midnight-memories",
    images: [
      {
        url: "https://picsum.photos/200",
        height: 200,
        width: 200,
      },
    ],
    tracks: [
      {
        images: mockTracks[0].images,
        duration_ms: mockTracks[0].duration_ms,
        id: mockTracks[0].id,
        name: mockTracks[0].name,
        track_number: mockTracks[0].track_number,
      },
      {
        images: mockTracks[1].images,
        duration_ms: mockTracks[1].duration_ms,
        id: mockTracks[1].id,
        name: mockTracks[1].name,
        track_number: mockTracks[1].track_number,
      },
      {
        images: mockTracks[2].images,
        duration_ms: mockTracks[2].duration_ms,
        id: mockTracks[2].id,
        name: mockTracks[2].name,
        track_number: mockTracks[2].track_number,
      },
    ],
    type: "album",
    uploadTime: "2023-06-15T08:30:00.000Z",
    status: "published",
  },
  {
    id: "alb_002",
    name: "Acoustic Sessions",
    total_tracks: 4,
    href: "/album/acoustic-sessions",
    images: [
      {
        url: "https://picsum.photos/200",
        height: 200,
        width: 200,
      },
    ],
    tracks: [
      {
        images: mockTracks[1].images,
        duration_ms: mockTracks[1].duration_ms,
        id: mockTracks[1].id,
        name: mockTracks[1].name,
        track_number: mockTracks[1].track_number,
      },
      {
        images: mockTracks[2].images,
        duration_ms: mockTracks[2].duration_ms,
        id: mockTracks[2].id,
        name: mockTracks[2].name,
        track_number: mockTracks[2].track_number,
      },
      {
        images: mockTracks[3].images,
        duration_ms: mockTracks[3].duration_ms,
        id: mockTracks[3].id,
        name: mockTracks[3].name,
        track_number: mockTracks[3].track_number,
      },
      {
        images: mockTracks[4].images,
        duration_ms: mockTracks[4].duration_ms,
        id: mockTracks[4].id,
        name: mockTracks[4].name,
        track_number: mockTracks[4].track_number,
      },
    ],
    type: "album",
    uploadTime: "2023-09-20T14:45:00.000Z",
    status: "published",
  },
  {
    id: "alb_003",
    name: "Electronic Dreams",
    total_tracks: 5,
    href: "/album/electronic-dreams",
    images: [
      {
        url: "https://picsum.photos/200",
        height: 200,
        width: 200,
      },
    ],
    tracks: [
      {
        images: mockTracks[0].images,
        duration_ms: mockTracks[0].duration_ms,
        id: mockTracks[0].id,
        name: mockTracks[0].name,
        track_number: mockTracks[0].track_number,
      },
      {
        images: mockTracks[1].images,
        duration_ms: mockTracks[1].duration_ms,
        id: mockTracks[1].id,
        name: mockTracks[1].name,
        track_number: mockTracks[1].track_number,
      },
      {
        images: mockTracks[2].images,
        duration_ms: mockTracks[2].duration_ms,
        id: mockTracks[2].id,
        name: mockTracks[2].name,
        track_number: mockTracks[2].track_number,
      },
      {
        images: mockTracks[3].images,
        duration_ms: mockTracks[3].duration_ms,
        id: mockTracks[3].id,
        name: mockTracks[3].name,
        track_number: mockTracks[3].track_number,
      },
      {
        images: mockTracks[4].images,
        duration_ms: mockTracks[4].duration_ms,
        id: mockTracks[4].id,
        name: mockTracks[4].name,
        track_number: mockTracks[4].track_number,
      },
      {
        images: mockTracks[0].images,
        duration_ms: mockTracks[0].duration_ms,
        id: mockTracks[0].id,
        name: mockTracks[0].name,
        track_number: mockTracks[0].track_number,
      },
      {
        images: mockTracks[1].images,
        duration_ms: mockTracks[1].duration_ms,
        id: mockTracks[1].id,
        name: mockTracks[1].name,
        track_number: mockTracks[1].track_number,
      },
      {
        images: mockTracks[2].images,
        duration_ms: mockTracks[2].duration_ms,
        id: mockTracks[2].id,
        name: mockTracks[2].name,
        track_number: mockTracks[2].track_number,
      },
      {
        images: mockTracks[3].images,
        duration_ms: mockTracks[3].duration_ms,
        id: mockTracks[3].id,
        name: mockTracks[3].name,
        track_number: mockTracks[3].track_number,
      },
      {
        images: mockTracks[4].images,
        duration_ms: mockTracks[4].duration_ms,
        id: mockTracks[4].id,
        name: mockTracks[4].name,
        track_number: mockTracks[4].track_number,
      },
      {
        images: mockTracks[0].images,
        duration_ms: mockTracks[0].duration_ms,
        id: mockTracks[0].id,
        name: mockTracks[0].name,
        track_number: mockTracks[0].track_number,
      },
      {
        images: mockTracks[1].images,
        duration_ms: mockTracks[1].duration_ms,
        id: mockTracks[1].id,
        name: mockTracks[1].name,
        track_number: mockTracks[1].track_number,
      },
      {
        images: mockTracks[2].images,
        duration_ms: mockTracks[2].duration_ms,
        id: mockTracks[2].id,
        name: mockTracks[2].name,
        track_number: mockTracks[2].track_number,
      },
      {
        images: mockTracks[3].images,
        duration_ms: mockTracks[3].duration_ms,
        id: mockTracks[3].id,
        name: mockTracks[3].name,
        track_number: mockTracks[3].track_number,
      },
      {
        images: mockTracks[4].images,
        duration_ms: mockTracks[4].duration_ms,
        id: mockTracks[4].id,
        name: mockTracks[4].name,
        track_number: mockTracks[4].track_number,
      },
    ],
    type: "album",
    uploadTime: "2024-01-08T10:15:00.000Z",
    status: "hidden",
  },
  {
    id: "alb_004",
    name: "Summer Vibes",
    total_tracks: 3,
    href: "/album/summer-vibes",
    images: [
      {
        url: "https://picsum.photos/200",
        height: 200,
        width: 200,
      },
    ],
    tracks: [
      {
        images: mockTracks[2].images,
        duration_ms: mockTracks[2].duration_ms,
        id: mockTracks[2].id,
        name: mockTracks[2].name,
        track_number: mockTracks[2].track_number,
      },
      {
        images: mockTracks[3].images,
        duration_ms: mockTracks[3].duration_ms,
        id: mockTracks[3].id,
        name: mockTracks[3].name,
        track_number: mockTracks[3].track_number,
      },
      {
        images: mockTracks[4].images,
        duration_ms: mockTracks[4].duration_ms,
        id: mockTracks[4].id,
        name: mockTracks[4].name,
        track_number: mockTracks[4].track_number,
      },
    ],
    type: "EP",
    uploadTime: "2024-03-22T16:20:00.000Z",
    status: "published",
  },
  {
    id: "alb_005",
    name: "Unreleased Collection",
    total_tracks: 4,
    href: "/album/unreleased-collection",
    images: [
      {
        url: "https://picsum.photos/200",
        height: 200,
        width: 200,
      },
    ],
    tracks: [
      {
        images: mockTracks[5].images,
        duration_ms: mockTracks[5].duration_ms,
        id: mockTracks[5].id,
        name: mockTracks[5].name,
        track_number: mockTracks[5].track_number,
      },
      {
        images: mockTracks[0].images,
        duration_ms: mockTracks[0].duration_ms,
        id: mockTracks[0].id,
        name: mockTracks[0].name,
        track_number: mockTracks[0].track_number,
      },
      {
        images: mockTracks[1].images,
        duration_ms: mockTracks[1].duration_ms,
        id: mockTracks[1].id,
        name: mockTracks[1].name,
        track_number: mockTracks[1].track_number,
      },
      {
        images: mockTracks[2].images,
        duration_ms: mockTracks[2].duration_ms,
        id: mockTracks[2].id,
        name: mockTracks[2].name,
        track_number: mockTracks[2].track_number,
      },
    ],
    type: "compilation",
    uploadTime: "2024-05-10T09:00:00.000Z",
    status: "hidden",
  },
];

export {
  mockData,
  mockPlaylists,
  mockAlbums,
  mockArtists,
  mockTracks,
  mockArtistTracks,
  mockArtistAlbums,
};
